# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=<YourToken>

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET Categories
GET {{Web_HostAddress}}/api/Categories
Authorization: Bearer {{BearerToken}}

###

# POST Categories
POST {{Web_HostAddress}}/api/Categories
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateCategoryCommand
{
  "Name": "Backlog"
}

###

# PUT Categories
PUT {{Web_HostAddress}}/api/Categories/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateCategoryCommand
{
  "Id": 1,
  "Name": "Product Backlog"
}

###

# DELETE Categories
DELETE {{Web_HostAddress}}/api/Categories/1
Authorization: Bearer {{BearerToken}}

###

# GET Products
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/Products?CategoryId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}

Authorization: Bearer {{BearerToken}}

###

# POST Products
POST {{Web_HostAddress}}/api/Products
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateProductCommand
{
  "CategoryId": 1,
  "Name": "Eat a burrito 🌯"
}

###

#PUT Products UpdateItemDetails
PUT {{Web_HostAddress}}/api/Products/UpdateItemDetails?Id=1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateProductDetailCommand
{
  "Id": 1,
  "CategoryId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT Products
PUT {{Web_HostAddress}}/api/Products/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateProductCommand
{
  "Id": 1,
  "Name": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE Product
DELETE {{Web_HostAddress}}/api/Products/1
Authorization: Bearer {{BearerToken}}

###